resource_registry:
  #OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: ../nic-configs-dsal/computeovsdpdk.yaml
  OS::TripleO::ComputeOvsDpdkSriov::Net::SoftwareConfig: ../nic-configs-dsal/computeovsdpdksriov.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ../nic-configs-dsal/controller.yaml
  OS::TripleO::NodeExtraConfigPost: post-install.yaml

parameter_defaults:
  ControlPlaneDefaultRoute: "172.18.0.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19']
  EC2MetadataIp: "172.18.0.1"

  ExternalAllocationPools: [{'start': '10.9.88.200', 'end': '10.9.88.211'}]
  ExternalNetCidr: "10.9.88.0/24"
  #ExternalNetworkVlanID: 135
  NeutronExternalNetworkBridge: "''"
  ExternalInterfaceDefaultRoute: "10.9.88.254"

  InternalApiNetCidr: 100.30.81.0/24                                            
  StorageNetCidr: 100.30.82.0/24                                                
  StorageMgmtNetCidr: 100.30.83.0/24                                            
  TenantNetCidr: 100.30.84.0/24                                                 
  InternalApiNetworkVlanID: 131                                                 
  StorageNetworkVlanID: 132                                                     
  StorageMgmtNetworkVlanID: 133                                                 
  TenantNetworkVlanID: 134                                                      
  InternalApiAllocationPools: [{'start': '100.30.81.10', 'end': '100.30.81.200'}]
  StorageAllocationPools: [{'start': '100.30.82.10', 'end': '100.30.82.200'}]   
  StorageMgmtAllocationPools: [{'start': '100.30.83.10', 'end': '100.30.83.200'}]
  TenantAllocationPools: [{'start': '100.30.84.10', 'end': '100.30.84.200'}]

  #NeutronNetworkVLANRanges translates to neutron::plugins::ml2::network_vlan_ranges

  NeutronNetworkVLANRanges: "tenant_dpdk:210:214,tenant:230:234"
  NeutronPhysicalDevMappings: "tenant:p1p2"
  NovaPCIPassthrough:
    - devname: "p1p2"
      physical_network: "tenant"
  NeutronSriovNumVFs: "p1p2:5"
